name: Deploy to Private S3

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change this to your desired AWS region

    # - name: Ensure index_files directory exists
    #   run: |
    #     mkdir -p index_files

    - name: s3 deploy directory
      run: |
        aws s3 sync --recursive index_files/ s3://cd-corp-website-dev/index_files 

    - name: s3 deploy index
      run: |
        aws s3 sync index.html s3://cd-corp-website-dev/ --acl private
        


    # - name: Generate pre-signed URL
    #   id: presigned-url
    #   run: |
    #     URL=$(aws s3 presign s3://cd-corp-website-dev/ --recursive --expires-in 3600)
    #     echo "::set-output name=url::$URL"

    # - name: Create CloudFront Invalidation
    #   run: |
    #     aws cloudfront create-invalidation --distribution-id E1B3CJVJ1KYPXJ --paths '/*'
    #   env:
    #     AWS_DEFAULT_REGION: us-east-1  # Change this to your desired AWS region
