name: Deploy to Private S3

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        node-version: '16'
        
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        node-version: '16'
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change this to your desired AWS region
        
    - name: jq tool
      run:  sudo apt-get install jq
      
    - name: List S3 objects
      id: list-objects
      run: |
        OBJECTS=$(aws s3api list-objects --bucket cd-corp-website-dev --query 'Contents[].Key' --output json || echo '[]')
        echo "List of objects: $OBJECTS"
        echo "::set-output name=objects::$OBJECTS"

    - name: Generate pre-signed URLs
      id: presigned-urls
      run: |
        OBJECTS=(${{ steps.list-objects.outputs.objects }})
        echo "Number of objects: ${#OBJECTS[@]}"
        for OBJECT in "${OBJECTS[@]}"; do
          echo "Processing object: $OBJECT"
          URL=$(aws s3 presign "s3://cd-corp-website-dev/$OBJECT" --expires-in 3600)
          echo "::set-output name=url::$URL"
        done

    - name: Deploy to S3
      run: |
        OBJECTS=(${{ steps.list-objects.outputs.objects }})
        for OBJECT in "${OBJECTS[@]}"; do
          aws s3 cp "index_files/$OBJECT" "s3://cd-corp-website-dev/$OBJECT" --acl private
        done
      env:
        AWS_DEFAULT_REGION: us-east-1  # Change this to your desired AWS region
